FROM python:3.9-bullseye

WORKDIR /app

COPY ./requirements.txt /app/requirements.txt

# install torch cpu
RUN pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cpu
RUN pip install -U -r /app/requirements.txt

COPY ./src /app/src

RUN wget https://www.dropbox.com/s/q8lax9ary32c7t9/pytorch_model.bin?dl=0# -O /app/src/deepmoji/model/pytorch_model.bin

ENV PORT 50051
CMD ["python3", "src/microv2/server.py"]