version: "3.7"

services:
  # model servicers
  internal:
    network_mode: host
    stop_grace_period: 1s
    build:
      dockerfile: rateboat/internal/Dockerfile
      context: .
    ports:
      - 50051:50051
  # host the queuing api
  rateboat.store:
    network_mode: host
    build:
      dockerfile: rateboat/web/store/Dockerfile
      context: .
    ports:
      - 50056:50056
  # host the public-facing web api
  rateboat.api:
    network_mode: host
    build:
      dockerfile: rateboat/web/api/Dockerfile
      context: .
    ports:
      - 8081:8081
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - 6379:6379
    command: redis-server
