version: "3.7"

services:
  # model servicers
  rateboat.internal:
    network_mode: host
    container_name: rateboat.internal
    build:
      dockerfile: rateboat/internal/Dockerfile
      context: .
    ports:
      - 50051:50051
  # host the queuing api
  rateboat.store:
    network_mode: host
    container_name: rateboat.store
    build:
      dockerfile: rateboat/web/store/Dockerfile
      context: .
    ports:
      - 50056:50056
