#!/bin/bash

set -e

function model {
  wget https://www.dropbox.com/s/q8lax9ary32c7t9/pytorch_model.bin?dl=0# -O \
  src/wordsmyth/data/pytorch_model.bin
}

TIMEFORMAT="Task completed in %3lR"
time model