#!venv/bin/python3

from click import group
from os import system


@group()
def cli():
    pass


@cli.command()
def dlmodel():
    """Download TorchMoji model for use"""
    from torchmoji.dl_utils import execute_download

    execute_download("src/deepmoji/model/pytorch_model.bin")


@cli.command()
def c():
    """Dev command!"""
    commit = input("Commit name: ")
    system(f'git commit -am "{commit}" && git push')


if __name__ == "__main__":
    cli()
