#!/bin/bash
PROTOC="python3 -m grpc_tools.protoc"
PY="python3"

set -e

function model {
    $PY -c \
		'from torchmoji.dl_utils import execute_download; \
		execute_download("./src/algo/deepmoji/model/pytorch_model.bin")'
}

function build {
    rm -rf $1
	mkdir $1
	$PROTOC -I $1 \
		--python_out=$1/stubs \
		--grpc_python_out=$1/stubs queue.proto \
		--mypy_out=$1/stubs
}

TIMEFORMAT="Task completed in %3lR"
time ${@:-default}