"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class Texts(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TEXTS_FIELD_NUMBER: builtins.int
    @property
    def texts(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        texts: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["texts", b"texts"]) -> None: ...

global___Texts = Texts

class Emoji(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    EMOJIS_FIELD_NUMBER: builtins.int
    TEXT_FIELD_NUMBER: builtins.int
    @property
    def emojis(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    text: builtins.str
    def __init__(
        self,
        *,
        emojis: collections.abc.Iterable[builtins.str] | None = ...,
        text: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["emojis", b"emojis", "text", b"text"]) -> None: ...

global___Emoji = Emoji

class Emojis(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RESPONSE_FIELD_NUMBER: builtins.int
    @property
    def response(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Emoji]: ...
    def __init__(
        self,
        *,
        response: collections.abc.Iterable[global___Emoji] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["response", b"response"]) -> None: ...

global___Emojis = Emojis

class NegNeuPos(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NEG_FIELD_NUMBER: builtins.int
    NEU_FIELD_NUMBER: builtins.int
    POS_FIELD_NUMBER: builtins.int
    neg: builtins.float
    neu: builtins.float
    pos: builtins.float
    def __init__(
        self,
        *,
        neg: builtins.float = ...,
        neu: builtins.float = ...,
        pos: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["neg", b"neg", "neu", b"neu", "pos", b"pos"]) -> None: ...

global___NegNeuPos = NegNeuPos

class Sentiment(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SENTIMENT_FIELD_NUMBER: builtins.int
    TEXT_FIELD_NUMBER: builtins.int
    @property
    def sentiment(self) -> global___NegNeuPos: ...
    text: builtins.str
    def __init__(
        self,
        *,
        sentiment: global___NegNeuPos | None = ...,
        text: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["sentiment", b"sentiment"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["sentiment", b"sentiment", "text", b"text"]) -> None: ...

global___Sentiment = Sentiment

class Sentiments(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RESPONSE_FIELD_NUMBER: builtins.int
    @property
    def response(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Sentiment]: ...
    def __init__(
        self,
        *,
        response: collections.abc.Iterable[global___Sentiment] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["response", b"response"]) -> None: ...

global___Sentiments = Sentiments
