# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cserver.proto\x12\x06models\"\x16\n\x05Texts\x12\r\n\x05texts\x18\x01 \x03(\t\"%\n\x05\x45moji\x12\x0e\n\x06\x65mojis\x18\x01 \x03(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\")\n\x06\x45mojis\x12\x1f\n\x08response\x18\x01 \x03(\x0b\x32\r.models.Emoji\"2\n\tNegNeuPos\x12\x0b\n\x03neg\x18\x01 \x01(\x02\x12\x0b\n\x03neu\x18\x02 \x01(\x02\x12\x0b\n\x03pos\x18\x03 \x01(\x02\"?\n\tSentiment\x12$\n\tsentiment\x18\x01 \x01(\x0b\x32\x11.models.NegNeuPos\x12\x0c\n\x04text\x18\x02 \x01(\t\"1\n\nSentiments\x12#\n\x08response\x18\x01 \x03(\x0b\x32\x11.models.Sentiment2e\n\x05Model\x12,\n\ttorchmoji\x12\r.models.Texts\x1a\x0e.models.Emojis\"\x00\x12.\n\x07roberta\x12\r.models.Texts\x1a\x12.models.Sentiments\"\x00\x62\x06proto3')



_TEXTS = DESCRIPTOR.message_types_by_name['Texts']
_EMOJI = DESCRIPTOR.message_types_by_name['Emoji']
_EMOJIS = DESCRIPTOR.message_types_by_name['Emojis']
_NEGNEUPOS = DESCRIPTOR.message_types_by_name['NegNeuPos']
_SENTIMENT = DESCRIPTOR.message_types_by_name['Sentiment']
_SENTIMENTS = DESCRIPTOR.message_types_by_name['Sentiments']
Texts = _reflection.GeneratedProtocolMessageType('Texts', (_message.Message,), {
  'DESCRIPTOR' : _TEXTS,
  '__module__' : 'server_pb2'
  # @@protoc_insertion_point(class_scope:models.Texts)
  })
_sym_db.RegisterMessage(Texts)

Emoji = _reflection.GeneratedProtocolMessageType('Emoji', (_message.Message,), {
  'DESCRIPTOR' : _EMOJI,
  '__module__' : 'server_pb2'
  # @@protoc_insertion_point(class_scope:models.Emoji)
  })
_sym_db.RegisterMessage(Emoji)

Emojis = _reflection.GeneratedProtocolMessageType('Emojis', (_message.Message,), {
  'DESCRIPTOR' : _EMOJIS,
  '__module__' : 'server_pb2'
  # @@protoc_insertion_point(class_scope:models.Emojis)
  })
_sym_db.RegisterMessage(Emojis)

NegNeuPos = _reflection.GeneratedProtocolMessageType('NegNeuPos', (_message.Message,), {
  'DESCRIPTOR' : _NEGNEUPOS,
  '__module__' : 'server_pb2'
  # @@protoc_insertion_point(class_scope:models.NegNeuPos)
  })
_sym_db.RegisterMessage(NegNeuPos)

Sentiment = _reflection.GeneratedProtocolMessageType('Sentiment', (_message.Message,), {
  'DESCRIPTOR' : _SENTIMENT,
  '__module__' : 'server_pb2'
  # @@protoc_insertion_point(class_scope:models.Sentiment)
  })
_sym_db.RegisterMessage(Sentiment)

Sentiments = _reflection.GeneratedProtocolMessageType('Sentiments', (_message.Message,), {
  'DESCRIPTOR' : _SENTIMENTS,
  '__module__' : 'server_pb2'
  # @@protoc_insertion_point(class_scope:models.Sentiments)
  })
_sym_db.RegisterMessage(Sentiments)

_MODEL = DESCRIPTOR.services_by_name['Model']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TEXTS._serialized_start=24
  _TEXTS._serialized_end=46
  _EMOJI._serialized_start=48
  _EMOJI._serialized_end=85
  _EMOJIS._serialized_start=87
  _EMOJIS._serialized_end=128
  _NEGNEUPOS._serialized_start=130
  _NEGNEUPOS._serialized_end=180
  _SENTIMENT._serialized_start=182
  _SENTIMENT._serialized_end=245
  _SENTIMENTS._serialized_start=247
  _SENTIMENTS._serialized_end=296
  _MODEL._serialized_start=298
  _MODEL._serialized_end=399
# @@protoc_insertion_point(module_scope)
