# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import internal.stubs.server_pb2 as server__pb2


class ModelStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.torchmoji = channel.stream_stream(
            "/models.Model/torchmoji",
            request_serializer=server__pb2.Request.SerializeToString,
            response_deserializer=server__pb2.Emoji.FromString,
        )
        self.flair = channel.stream_stream(
            "/models.Model/flair",
            request_serializer=server__pb2.Request.SerializeToString,
            response_deserializer=server__pb2.Sentiment.FromString,
        )


class ModelServicer(object):
    """Missing associated documentation comment in .proto file."""

    def torchmoji(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def flair(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_ModelServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "torchmoji": grpc.stream_stream_rpc_method_handler(
            servicer.torchmoji,
            request_deserializer=server__pb2.Request.FromString,
            response_serializer=server__pb2.Emoji.SerializeToString,
        ),
        "flair": grpc.stream_stream_rpc_method_handler(
            servicer.flair,
            request_deserializer=server__pb2.Request.FromString,
            response_serializer=server__pb2.Sentiment.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "models.Model", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class Model(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def torchmoji(
        request_iterator,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            "/models.Model/torchmoji",
            server__pb2.Request.SerializeToString,
            server__pb2.Emoji.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def flair(
        request_iterator,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            "/models.Model/flair",
            server__pb2.Request.SerializeToString,
            server__pb2.Sentiment.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
