# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cserver.proto\x12\x06models\"\'\n\x07Request\x12\r\n\x05texts\x18\x01 \x03(\t\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\"%\n\x05\x45moji\x12\x0e\n\x06\x65mojis\x18\x01 \x03(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\"-\n\tIntensity\x12\x11\n\tsentiment\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x02\"?\n\tSentiment\x12$\n\tsentiment\x18\x01 \x01(\x0b\x32\x11.models.Intensity\x12\x0c\n\x04text\x18\x02 \x01(\t2m\n\x05Model\x12\x31\n\ttorchmoji\x12\x0f.models.Request\x1a\r.models.Emoji\"\x00(\x01\x30\x01\x12\x31\n\x05\x66lair\x12\x0f.models.Request\x1a\x11.models.Sentiment\"\x00(\x01\x30\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'server_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUEST._serialized_start=24
  _REQUEST._serialized_end=63
  _EMOJI._serialized_start=65
  _EMOJI._serialized_end=102
  _INTENSITY._serialized_start=104
  _INTENSITY._serialized_end=149
  _SENTIMENT._serialized_start=151
  _SENTIMENT._serialized_end=214
  _MODEL._serialized_start=216
  _MODEL._serialized_end=325
# @@protoc_insertion_point(module_scope)
