# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import web.store.stubs.queue_pb2 as queue__pb2


class QueueStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.check_queue = channel.unary_unary(
                '/queue.Queue/check_queue',
                request_serializer=queue__pb2.Request.SerializeToString,
                response_deserializer=queue__pb2.QueueStatus.FromString,
                )


class QueueServicer(object):
    """Missing associated documentation comment in .proto file."""

    def check_queue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QueueServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'check_queue': grpc.unary_unary_rpc_method_handler(
                    servicer.check_queue,
                    request_deserializer=queue__pb2.Request.FromString,
                    response_serializer=queue__pb2.QueueStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'queue.Queue', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Queue(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def check_queue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/queue.Queue/check_queue',
            queue__pb2.Request.SerializeToString,
            queue__pb2.QueueStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
