name: publish

on: [push]

jobs:
  publish-images:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build all Docker images
      run: |
        docker build . -f ./rateboat/internal/Dockerfile --tag ghcr.io/themysticsavages/rateboat.internal:latest
        docker push ghcr.io/themysticsavages/rateboat.internal:latest
        docker build . -f ./rateboat/web/store/Dockerfile --tag ghcr.io/themysticsavages/rateboat.store:latest
        docker push ghcr.io/themysticsavages/rateboat.store:latest
        docker build . -f ./rateboat/web/application/Dockerfile --tag ghcr.io/themysticsavages/rateboat.web:latest
        docker push ghcr.io/themysticsavages/rateboat.web:latest