on: 
  push:
    branches:
      - minimal
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'

jobs:
  release-on-push:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - id: get-commit-level
        run: |
          commit=$(echo ${{ github.event.head_commit.message }} | grep -Po '\[\K[^]]*')
          echo "::set-output name=commit::$commit"
      - id: stuff
        run: echo "${{steps.get-commit-level.outputs.commit}}"
