on: 
  push:
    branches:
      - minimal
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'

jobs:
  release-on-push:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Bump version
        id: get-commit-level
        run: |
          commit=$(echo ${{ github.event.head_commit.message }} | grep -Po '\[\K[^]]*')
          echo "::set-output name=commit::$commit"
      - name: Push version
        uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: ${{steps.get-commit-level.outputs.commit}}
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Build package wheel
        run: |
          python -m pip install cibuildwheel==2.12.3
          python -m cibuildwheel --output-dir dist

      - uses: actions/upload-artifact@v3
        with:
          path: ./dist/*.whl