on: 
  push:
    branches:
      - minimal
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  

jobs:
  release-on-push:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - id: get-commit-level
      run: |
        commit=$(echo ${{ github.event.head_commit.message }} | grep -P '\[.*?\]')
        echo "::set-output name=commit::$commit"
      - run: echo "${{steps.get-commit-level.outputs.commit}}"
      if: contains(${{ github.event.head_commit.message }}, '[patch]')
        - uses: rymndhng/release-on-push-action@master
          with:
            bump_version_scheme: patch
      if: contains(${{ github.event.head_commit.message }}, '[minor]')
        - uses: rymndhng/release-on-push-action@master
          with:
            bump_version_scheme: minor