on: 
  push:
    branches:
      - minimal
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'

jobs:
  release-on-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Build package"
        run: |
          python3 -m pip install -U build
          python3 -m build
      - uses: xresloader/upload-to-github-release@v1
        name: "Upload archives to GitHub release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "dist/*"
          tags: true
          draft: true