name: Run tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps: 
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            src:
              - 'src/**'
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
          
      - if: steps.changes.outputs.src == 'true'
        name: 'Run tests'
        run: |
          python -m pip install --upgrade pip
          pip install -U setuptools wheel
          pip install -r requirements_dev.txt
          pip install torch --extra-index-url https://download.pytorch.org/whl/cpu
          wget -q https://www.dropbox.com/s/q8lax9ary32c7t9/pytorch_model.bin?dl=0# -O ./src/algo/deepmoji/model/pytorch_model.bin
          pytest
