name: Run tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps: 
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
      - uses: actions/setup-python@v2
      - uses: actions/setup-python@v2
        id: changes
        with:
          python-version: '3.9'
          cache: 'pip'
          filters: |
            src:
              - 'src/**'
      - if: steps.changes.outputs.src == 'true'
        name: 'Run tests'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_dev.txt
          pip install torch --extra-index-url https://download.pytorch.org/whl/cpu
          pip install -r requirements.txt
