name: Run tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps: 
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            src:
              - 'src/**'

          # run only if some file in 'src' folder was changed
      - if: steps.changes.outputs.src == 'true'
        run: echo "Hello wold"
